all : kohonen

kohonen: kohonen.c base_opengl.h kohonen.h
	gcc /System/Library/Frameworks/GLUT.framework/GLUT /System/Library/Frameworks/OpenGL.framework/OpenGL  -o kohonen kohonen.c


clean :
	rm -f kohonen *.o